name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: "Test: Mongoid ${{ matrix.mongoid }} on Ruby ${{ matrix.ruby }}"
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    strategy:
      fail-fast: false
      matrix:
        include:
          - mongoid: 7.5
            ruby: 2.7
          - mongoid: 7.5
            ruby: "3.0"

          - mongoid: 8.0
            ruby: 3.1

          - mongoid: 8.1
            ruby: 3.1
          - mongoid: 8.1
            ruby: 3.2

    env:
      BUNDLE_GEMFILE: gemfiles/mongoid_${{ matrix.mongoid }}.gemfile
      DISPLAY: ":99.0"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Gemfile
        run: echo $BUNDLE_GEMFILE

      - name: Ruby Version
        run: ruby --version

      - name: Run Tests
        run: bundle exec rake test
